apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-file-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  # Depends on NFS service
  storageClassName: nfs